### ISSUE TITLE
feature-request: expand settings-stats

### ISSUE THREAD

**Issue by Tinsus** [solorey/Art-Saver#10]
Hi there,

could you please add the function, that opens, when I click on the url-bar-icon and than on the Users saved or submissions saved field also to the settings, where exactly this fields also exist

**Comment by solorey** [comment]
Could you expand more on this request?

**Comment by Tinsus** [comment]
sorry for the late reply - yes I need to explain this. It's only a very minor thing.

If you click on the URL-bar-icon you can click on users saved or submission saved to see a list of them.
If you are in the settings for this addon in the top you see a list, but you can not click the numbers to see the information you get from the url-bar-button.

By the way: I would like to offer you to give you a translation to German if you like.
