### ISSUE TITLE
Pixiv download only working on home page?

### ISSUE THREAD

**Issue by TacoCake** [solorey/Art-Saver#12]
The prompt to download (the little check box to the top left of the thumbnail) is only available on the home page [https://www.pixiv.net/en](https://www.pixiv.net/en)

Anyother page shows

> Unable to get site information.
> Make` sure you are on a supported site and the page is fully loaded.

### Expected Behaviour
Any artwork should show the little checkmark

### Actual Behaviour
It doesn't appear
For [example](https://www.pixiv.net/en/artworks/88293567)

**Comment by solorey** [comment]
Can confirm this issue. Updated and should be fixed now in v1.5.4

**Comment by TacoCake** [comment]
I can confirm that it works again now, thanks!
