### ISSUE TITLE
version 1.5.4 firefox

### ISSUE THREAD

**Issue by AmadeusLight** [solorey/Art-Saver#13]
In this version it loses compatibility with another extension called minipixiv that allowed me to download pixiv images within another more minimalist window. 

![AFTER](https://user-images.githubusercontent.com/70249580/113916480-e05bd200-9794-11eb-91e0-39061bb5806f.png)
![before](https://user-images.githubusercontent.com/70249580/113916485-e2259580-9794-11eb-8e5c-9b64a1a76dbf.png)

**Comment by solorey** [comment]
Honestly surprised it even worked at all. This extension is sensitive to layout changes and it seems this extension redoes the whole interface.
You're free to request support for Mini Pixiv however supporting custom layouts from other sources is not a current priority.
