### ISSUE TITLE
Settings location

### ISSUE THREAD

**Issue by zerobaka** [solorey/Art-Saver#2]
Please tell me where it is:
Storage: Used to save and store "information on what submissions were downloaded"
I wish to back it up and use it on another pc.
Thanks man.

**Comment by solorey** [comment]
The settings can be located in about:addons > Extensions > Art Saver > Options or opened by clicking the gear in the address bar popup. 

Information about what is currently saved can be backed up by clicking the Export button in the Global section.
![storage export](https://user-images.githubusercontent.com/48976970/82419249-bd70e400-9a43-11ea-8739-b632fc9209f8.png)
You can also export the settings by clicking the Export Settings button located at the bottom of the options page.
Hope this helps.
