### ISSUE TITLE
Wait time between downloads not working on DA?

### ISSUE THREAD

**Issue by byteshuffle** [solorey/Art-Saver#21]
I have the "Wait time between downloads" set to 2, because of (recent?) download throttling limit triggering frequently on deviantart (download too many per minute or so -> temporary 403 forbidden/blocked error)
But when I click on several pics to download, it queues and downloads them right after each other, without waiting...

**Comment by solorey** [comment]
0f5c220aa0514331d93125a42dcfc4cff5fd6a2a
Somehow was using the wrong key name. Should be working now in v1.7.6
