### ISSUE TITLE
feature request: automatic download

### ISSUE THREAD

**Issue by byteshuffle** [solorey/Art-Saver#22]
The ability to turn on automatic add to download queue each image it sees while scrolling through galleries or search results, so without clicking each image/hovering+d.

**Comment by byteshuffle** [comment]
I already got it working nicely in a test setup; just scroll through a page and all gets queued for download :)

`diff -Naur orig/content_scripts/classes.js  new/content_scripts/classes.js 
@@ -254,6 +254,8 @@
 		document.addEventListener('keypress', this.keypress_reference);
 
 		globalbuttons.addButton(this);
+
+		globalqueue.addDownload(this.site, this.submission_id);
 	}
 	clickEvent(event) {
 		event.preventDefault();
@@ -628,4 +630,4 @@
 		this.setProgress(10, 2, 3);
 		this.show();
 	}
`

TODO: add an if statement for and a on-off switch in settings.

**Comment by byteshuffle** [comment]
Previously I always selectively clicked on interesting deviations but now that I've seen too many deactivated accounts (and removed content thereof) added on my todo list some time ago, I just want to archive all faster and then delete what I don't like.

I regularly view/download deviants with 8K+ deviations so now together with the "auto-scroll" addon, I can leave it running on it's own to get all deviations without pressing the END key constantly.

**Comment by solorey** [comment]
Automatic downloading is not a feature that is planned to be implemented. However there is now a shortcut that can be set to download all submissions that are found on a page.
