### ISSUE TITLE
Updated Version of FA causes Problems.

### ISSUE THREAD

**Issue by Aetherios-Dragon** [solorey/Art-Saver#23]
Woult it be possible to upgrade the programm so that the new user structure and data base of Furaffinity could be working again?

**Comment by solorey** [comment]
Thanks for the update on the site change. I've updated the extension so that it should work for Fur Affinity again in v1.7.7

**Comment by Aetherios-Dragon** [comment]
It works perfectly. Thank you once more VERY VERY much. If there is some way to support or tip you for the awesome programm let me know.
