### ISSUE TITLE
Stopped working on Furfaffinity a few days ago

### ISSUE THREAD

**Issue by Aetherios-Dragon** [solorey/Art-Saver#24]
Greetings once more. 
Could you please check and or varify if the application is still running on Furaffinity? For me it fully stopped working a few days ago. The UI does not show anymore and when I am on Artists Galleries, it tries to load the information...but never finishes it.

**Comment by solorey** [comment]
The extension is still currently working for me on Fur Affinity. Is there any additional information you can give about what is happening?

**Comment by Aetherios-Dragon** [comment]
Thank you very much for the quick response.
Yiss~ I can give you a bit more information. On FA it seems to not work anymore at all. I can hover over submissions and press D and the download won't start. With the application icon in the Adress-bar it's the same. It does not show any Saved information or even Artist Gallery stats.
I will add a screenshot of that here. [Art Saver 1.jpg]
You can see it loads...but never gets anything.

When I go into the Options and check for the saved users...it's all empty as well:
[Art Saver 2 FA.jpg]

But when I for example take another Site like Deviantart:
[Art Saver 3 DA.jpg]
I can see the user stats.

[Art Saver 4 DA.jpg]
And also the saved information.

Though even then when I go into the options the same like in the second screenshot.
Do you have any idea what this could have caused and how to fix it again?

Roar Loud! Walk Tall!
~Aetherios~

------- Original Message -------
solorey ***@***.***> schrieb am Donnerstag, 22. Dezember 2022 um 04:22:

**Comment by solorey** [comment]
It seems the screenshots did not transfer over from the email. Could you send them again using GitHub?

**Comment by Aetherios-Dragon** [comment]
I tried to embed them. Trying sending again

**Comment by Aetherios-Dragon** [comment]
Here you go. Files in Attachments. Let me know if you can open them now.

Roar Loud! Walk Tall!
~Aetherios~

------- Original Message -------
Teliko ***@***.***> schrieb am Donnerstag, 22. Dezember 2022 um 21:07:

> I tried to embed them. Trying sending again
>

**Comment by solorey** [comment]
It appears attachments are not sent when replying though email. Try drag and dropping them in a comment. https://github.com/solorey/Art-Saver/issues/24

**Comment by Aetherios-Dragon** [comment]
![Art Saver 1](https://user-images.githubusercontent.com/101025700/209311190-33576190-6bd7-4226-a097-6fc96d87f1cc.jpg)
![Art Saver 2 FA](https://user-images.githubusercontent.com/101025700/209311193-8900b1c7-eae4-404e-9400-7798217c7b94.jpg)
![Art Saver 3 DA](https://user-images.githubusercontent.com/101025700/209311195-c553ea94-4a3f-4b17-ba47-9b1fd7067307.jpg)
![Art Saver 4 DA](https://user-images.githubusercontent.com/101025700/209311197-a070c766-69eb-486b-8cd7-2368a42fc0db.jpg)

**Comment by Aetherios-Dragon** [comment]
Here you go

**Comment by solorey** [comment]
I see them now thank you. Does anything show in the console log on the setting page? You can open it when you're in the settings page with Ctrl+Shift+k

**Comment by Aetherios-Dragon** [comment]
You mean this? 
![Log ArtSaver](https://user-images.githubusercontent.com/101025700/209393890-a15e2efb-585a-4d4b-94bf-bcd3653d3dd3.jpg)

**Comment by solorey** [comment]
Hmm that error message is not really helpful. I suspect that there is a problem with your Fur Affinity data if the other sites still work for you. Is it possible to export your data? Does the error show again when doing so? Any new users you downloaded from before it stopped working with special characters in their name?

**Comment by Aetherios-Dragon** [comment]
That's all I can get out of it like this. 
but how can I repair the data then? I have the json-File of the saved users exported. Shall I load it into the programm again? 
It works on the other sites but does not show any information when you look at the programm settings, like you see on the big screen shot.

**Comment by solorey** [comment]
My first guess is there is something wrong with specifically the saved Fur Affinity data. If you have the exported data then you can try loading it into the program again to see if that fixes it.

**Comment by Aetherios-Dragon** [comment]
![Art Saver test](https://user-images.githubusercontent.com/101025700/209411416-d64eb502-531d-407b-89cd-d0bc62ea2722.jpg)

**Comment by Aetherios-Dragon** [comment]
Nothing happens when I do.

**Comment by solorey** [comment]
Try resetting the saved information. Then check if it works for Fur Affinity when you have no saved information. If it still doesn't work first export your settings and try removing then reinstalling the extension and see if it works for Fur Affinity before you add back your saved information.
