### ISSUE TITLE
DA, old watch

### ISSUE THREAD

**Issue by JasonHababou** [solorey/Art-Saver#26]
Hello, i tried to edit the module but i was not succesfull.
I would like to download my image on DA like i was doing in the paste using : https://www.deviantart.com/notifications/watch instead of https://www.deviantart.com/watch/deviations. 
Could you add the possibility to download from this path please ? 
"https://www.deviantart.com/notifications/watch"

**Comment by solorey** [comment]
The extension has been updated to show the buttons on this page in v1.7.9

**Comment by JasonHababou** [comment]
Hello, oh yes i got the surprise today. Thanks a lot. This Extension is so great.
