### ISSUE TITLE
Feature Request: Can't choose your default save folder/drive

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#27]
One of the things I love about Art Saver is that it automatically downloads images to sorted folders labeled by site and artist really fast without stopping to open up an Explorer window ask you where to "Save As" each time. It's very convenient. However, it always defaults to saving those folders on my C Drive, which is getting clogged because of it, instead of my external drive, where I have plenty of space. I figured there might be a way to change that in the Site Options, but the "Show Help" buttons don't provide a way to do that. If I had to choose, I'd rather keep doing things the way I have been than answer a "Save As" pop-up every time I want to save an image to a different drive with Art Saver. But I don't want to have to choose.

Is there any way a changeable default save location can be added to Art Saver's options menu?

**Comment by solorey** [comment]
WebExtensions are only allowed to automatically download in the default downloads folder. This folder is determined in your settings: `about:preferences#general`. If you want to change the location the images are saved there are a couple options.
1. Change the default downloads folder. This can be set to the external drive and all automatic downloads will be saved to the drive. However this of course will change the download location of all downloads not just this extension.
2. Create a symbolic link. The default downloads folder can stay the same but you can create a symbolic link folder in the downloads folder that links to the external drive. This pretends the location of the images are in the downloads folder but the data is actually saved in the external drive. On windows this is done using the `mklink /D` command.

**Comment by Mirrorman95** [comment]
> 
Thanks for the advice. I've changed the default install directory to my external drive, and that fixed it!
Issue resolved, Feature Request closed.
