### ISSUE TITLE
DeviantArt support failing (bug)

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#30]
Platform: Windows 10 (64-bit), Firefox 115.0 (64-bit)

I just tried using the ArtSaver to download all sorts of stuff on DeviantArt, but it no longer works there for some reason. I tried using a VPN, and it still didn't work. I tried downloading them in a private window where I wasn't logged in, still didn't work. I tried using it on all four of the other supported websites and they all downloaded images just fine like always, but not DeviantArt. I don't know what is going on. If someone could please help me figure this out, or come up with a fix, I would appreciate it.

**Comment by Houdini111** [comment]
I'm also seeing this issue now. Looks like it's failing in getMeta where the request parameter is saying that username is required. 

`{
"error":"invalid_request",
"errorDescription":"Request field validation failed.",
"errorDetails":{
    "username":"username is required"},
    "status":"error",
    "pageBiMetadata":"..."
}`

**Comment by solorey** [comment]
Thanks for the info. I submitted a hotfix that should fix this. v1.7.11

**Comment by Mirrorman95** [comment]
I'd like to reopen this issue as I am having the exact same symptoms as last time. Saving from DeviantArt isn't working for me at all.

**Comment by Houdini111** [comment]
Yep. Looks like it suddenly broke again. This time it seems that `await fetcher(`https://www.deviantart.com/_napi/shared_api/deviation/extended_fetch?${params}`, 'json')` is returning a 404 page

**Comment by solorey** [comment]
Seems like an API URL change. I'll look into it.

**Comment by Mirrorman95** [comment]
Yesterday, ArtSaver was working fine. But now, I'm not seeing the download arrows anywhere on DeviantArt. It still works fine on Inkbunny, Pixiv, and FurAffinity, but not DeviantArt.

**Comment by Mirrorman95** [comment]
I believe that https://github.com/solorey/Art-Saver/blob/master/content_scripts/sites/deviantart.js needs to be updated again in order to fix it. It is also possible that https://github.com/solorey/Art-Saver/blob/master/lib/purify.min.js may need to be updated, because I received this Warning message in the console when trying to run Art-Saver on a DeviantArt gallery:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://85dc4ca3-2dd4-43f4-919c-3613726c2d49/lib/purify.min.js
Source Map URL: purify.min.js.map
```

**Comment by solorey** [comment]
It seems the markup of the site has changed slightly but enough that the extension no longer knows where to put the download buttons. I'll add a patch soon.
As for the source map error. You can ignore it. Source map files just link between the minified and non-minified code to help with debugging. This extension just includes the minified code of the library.

**Comment by RVDDP2501** [comment]
Hi, please pardon and forgive my asking, how is the resolution of the issue progressing? :)

**Comment by Mirrorman95** [comment]
> Hi, please pardon and forgive my asking, how is the resolution of the issue progressing? :)

It got fixed 15 hours ago, RVDDP2501. Just update your extension and it'll work again. Good job, solorey.
I'll close the issue for now, but I'll make sure to reopen it again the next time this happens.

**Comment by solorey** [comment]
I added a patch v1.7.14 that should return the buttons on DeviantArt. Always feel free to let me know when a site changes/no longer works.

**Comment by RVDDP2501** [comment]
Hey! Yes, just saw your email and its back up and running! THANK YOU!!!!!!! J
