### ISSUE TITLE
Add option to set first page number to 0 to match official downloading naming scheme (Pixiv)

### ISSUE THREAD

**Issue by TacoCake** [solorey/Art-Saver#32]
When manually downloading an image from Pixiv (right click -> save image), the first image is always labelled as `p0`, whether it's a single image, or multiple images.

For single images, this is easily configurable, you can just set the pattern to something like `Saved/{site}/{submissionId}_p0.{ext}`.

However, for multiple images, you can't easily set the start number to 0.

I would love an option to set the starting number to 0 for multiple pages.

Thank you in advance!

**Comment by solorey** [comment]
The `{fileName}` meta will give the usual file name when manually saving. Also there is now new number modifiers in the new template syntax.
https://github.com/solorey/Art-Saver/wiki/Template-Syntax
