### ISSUE TITLE
DeviantArt side images issue (bug)

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#33]
Platform: Windows 10 (64-bit), Firefox 116.0.3 (64-bit)

I've been having this issue for several days now, I was just hoping that someone else would mention it here because I was afraid that it was just me. DeviantArt galleries and searches still work just fine for me with ArtSaver. But you know how whenever you look at an individual DeviantArt deviation, there are a bunch of thumbnails on the right side of it linking to other similar/recommended deviations, and ArtSaver used to show green checkmark download icons in the corners of all the ones you've already downloaded with it? Well, whenever I visit the webpage of an individual DeviantArt deviation nowadays, ArtSaver just sort of stacks all of the green checkmark download icons that're supposed to be on those thumbnails just slightly above and to the left of the Deviation's checkmark icon instead. Which means I can't download them with ArtSaver or check whether or not I already have from that page; I have to visit each of the thumbnails' pages individually to do that now. Is it just me? And if not, how would one fix it?

**Comment by solorey** [comment]
I can confirm this issue. Will update soon.

**Comment by solorey** [comment]
Should be fixed in v1.7.12
If any problems arise, let me know with a new issue.
