### ISSUE TITLE
Deviantart blocking?

### ISSUE THREAD

**Issue by RVDDP2501** [solorey/Art-Saver#34]
Hi, I have been using art saver for a week or so now, its been really helpful but now it doesn't seem to work on Deviantart anymore, I get the red warning icon whenever I try to download anything, I tried turning off my vpn and extended the delay between downloads and nothing helps :(
![artsave](https://github.com/solorey/Art-Saver/assets/146831911/03e5890b-b189-46dd-b187-6b6c8fa1cbb0)

**Comment by solorey** [comment]
https://github.com/solorey/Art-Saver/issues/30
