### ISSUE TITLE
Art Saver no longer working on Deviant Art?

### ISSUE THREAD

**Issue by RVDDP2501** [solorey/Art-Saver#35]
Hi, sorry to bother you but I tried to download some images and when I pass my mouse over them, the blue button no longer appears as well as previous images I downloaded no longer showing they have been downloaded. It works on the other sites it supports, just not DA :(

**Comment by Mirrorman95** [comment]
I've noticed this, too. And it seems to happen every few months. DeviantArt changes it's API in some way that stops Art-Saver from working with it, and we just make new issues about it here and wait, until eventually solorey notices and figures out what's wrong and puts out a fix for it, and then it works again for a good long while until it all happens again several months later.

**Comment by RVDDP2501** [comment]
> I've noticed this, too. And it seems to happen every few months. DeviantArt changes it's API in some way that stops Art-Saver from working with it, and we just make new issues about it here and wait, until eventually solorey notices and figures out what's wrong and puts out a fix for it, and then it works again for a good long while until it all happens again several months later.

Ah! I see, I hope it gets sorted out soon, some artists I follow mass upload batches of art which makes manually downloading it a real pain! :P

**Comment by Mirrorman95** [comment]
> > I've noticed this, too. And it seems to happen every few months. DeviantArt changes it's API in some way that stops Art-Saver from working with it, and we just make new issues about it here and wait, until eventually solorey notices and figures out what's wrong and puts out a fix for it, and then it works again for a good long while until it all happens again several months later.
> 
> Ah! I see, I hope it gets sorted out soon, some artists I follow mass upload batches of art which makes manually downloading it a real pain! :P
I hope so, too.

**Comment by solorey** [comment]
I can confirm this issue and left a comment here. https://github.com/solorey/Art-Saver/issues/30

**Comment by RVDDP2501** [comment]
Oh! Thank you! J

**Comment by solorey** [comment]
I added a patch v1.7.14 that should return the buttons on DeviantArt.
