### ISSUE TITLE
DeviantArt Literature thumbnails have no download button (bug)

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#36]
Platform: Windows 10 (64-bit), Firefox 122.0 (64-bit)
Art Saver version: 1.7.14

The 1.7.14 update fixed DeviantArt support for the most part. I can see and use the download button on DeviantArt gallery image thumbnails to download the full images. And I can see and use the download button on the corners of the titles of DeviantArt Literature deviations to download HTML versions of those stories. But I can only do that from the individual deviations' pages. If I hover over a thumbnail of a Literature deviation in its author's gallery, it still doesn't show a download button. Now, I rarely use that particular feature, so this is not a big deal for me, but it is a bug, so I'd appreciate it if you could please fix this at your earliest convenience.

**Comment by solorey** [comment]
Can confirm this issue. Added a patch v1.7.15 to return buttons to literature thumbnails as well.
