### ISSUE TITLE
DeviantArt: Some Stash links in the description don't get downloaded. (Bug)

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#37]
I had a problem with using ArtSaver to download the deviations at this link:
https://www.deviantart.com/csodaaut/art/JB-Sursulapitschi-turned-into-a-human-1029659142
Usually. ArtSaver downloads from the Stash links referred to in the description. But it didn't download from the one in this one's.
The link was: https://www.deviantart.com/stash/01t4wapkxyjn
I think it's because the base URL isn't "sta.sh/" like most Stash links I've seen are. Maybe the code that checks for DeviantArt Stash links in descriptions needs to be broadened to support it?

**Comment by solorey** [comment]
It seems Stash has finally been updated to match the rest of DeviantArt. I will need to update the Stash code due to the new Stash page layout.

**Comment by solorey** [comment]
I have updated the extension so it should now work with the new Stash page in v1.7.16.

**Comment by Mirrorman95** [comment]
> I have updated the extension so it should now work with the new Stash page in v1.7.16.

It seems to be working fine now. Thanks!

**Comment by Mirrorman95** [comment]
I just used ArtSaver on two deviations from the same user with the same kind of sta.sh links in their descriptions, but for some reason, it didn't download the sta.sh links this time. I honestly don't know how that's possible, but I hope it's the extension and not something wrong with my browser. Here is one of the deviations in question:
https://www.deviantart.com/csodaaut/art/My-OC-Sundaya-Daughter-of-the-Malayan-Tiger-1047867630

**Comment by solorey** [comment]
I can confirm the issue. Fix coming soon.

**Comment by solorey** [comment]
It should now pick up the links in v1.7.17.

**Comment by Mirrorman95** [comment]
> It should now pick up the links in v1.7.17.

Thanks! I don't entirely understand how/why that small single/double quotes change in the regex expression fixed it, but it works now, so it's all good.
