### ISSUE TITLE
Art Saver download options and button are missing

### ISSUE THREAD

**Issue by JerryRacqoon** [solorey/Art-Saver#40]
The download buttons have vanished from the sites and the options are also blank of any settings

**Comment by JerryRacqoon** [comment]
Uninstalled and then reinstalled and it fixed it

**Comment by solorey** [comment]
Based on the fact that the options are also blank it seems like the background of the extension stopped for some reason. I don't know what could have caused that but I'm glad reinstalling the extension resolved it.
Also nice legendary default profile picture.
