### ISSUE TITLE
Many folders for the same user ID (Pixiv)

### ISSUE THREAD

**Issue by Houdini111** [solorey/Art-Saver#43]
Over time, as users change their names, causing the connections with the previously downloaded art to break and also making it harder to find all the downloaded work from the same artist. 
I checked my folder and found about 17000 folders. Of those I found something like 1000 IDs with duplicate folders. The worst one I noticed had 10 different folders for the same user. 

I do not know what permissions the extension has or could have but I think the best solution would be:
1. Check for all folders ending in `_{ID}`. 
2. If there are more than one then rename all the folders (and all the files in the folder) to match the new name. 

I have attempted to mitigate this issue locally with the creation of a python 3 script (requiring the Python library BeautifulSoup 4 to also be installed). You can find the code at https://pastebin.com/RYA1Acqx. To run, ensure Python 3 and BS4 are installed and place the script in the ArtSaver/Pixiv folder. Run it  (`python3 dupeMerger.py`).
Because it's not going through the browser I can't assume that the name fetched from Pixiv will be match the output post-browser normalization. As such the script takes a less definitive approach. 
1. Get all IDs
2. Get all folders for each ID
3. If there is only one folder with that ID, ignore it
4. Get the current name of the user on Pixiv (call to the user page and extract it from the page Title). This is the step that requires BeautifulSoup4.
5. If there is a folder that matches the name, designate it as the one to merge to
6. If there is not, find the duplicate folder that was changed most recently (this is assumed to be their most recent name) and designate it as the destination.
7. Go through all duplicate folders and rename all files to use the destination folder's username (including album folders and the files inside)
8. Move those files to the destination folder
9. Delete the old folder
This process should provide the most accurate deduping possible unless browsers would externalize their save file normalization code.

**Comment by solorey** [comment]
Unfortunately local folder manipulation is outside of the scope of what web extensions are allowed to do.
For Pixiv I know that user names are changed frequently. However the user id should always be the same.
One way to ensure a single folder for an artist is to change the path to only include the user id.
Example: `Saved/{site}/{userName}_{userId}/` -> `Saved/{site}/{userId}/`
This of course does make it harder if you browse your artists by user name as user ids in Pixiv are only numbers.
If you want to include the user name in the folder then your solution is necessary. There is no way for the extension to know what folders you have on your machine.

**Comment by solorey** [comment]
For security reasons web extensions can't search for and edit local files on your system. Since you are familiar with Python I can offer some suggestions.

#### Suggestion 1: Use Python to create `usernames.txt`
1. Remove `{userName}` from the user folder but keep it in the file name. Example: `Saved/{site}/{userName}_{userId}/{submissionId}_by_{userName}.{ext}` -> `Saved/{site}/{userId}/{submissionId}_by_{userName}.{ext}`. This will keep all the submissions in the same user folder even if the user name changes.
2. Use Python to go through each user folder, extract the user name from the file names, then create a `usernames.txt` that contains a list of every unique user name.
3. Run the script periodically.

#### Suggestion 2: Save to a temporary folder then move
1. Keep the original `Saved/{site}/{userName}_{userId}/` location.
2. Have this extension save new submissions to a temporary location. Example: `Saved/{site}_temp/{userName}_{userId}/`.
3. For each user folder in the temp location, use Python to
    1. Find a user folder in the original location that has the same user id.
    2. If one doesn't exist create one.
    3. If the user name in the original location doesn't match rename the user folder in the original location using the new user name.
    4. Move the files in the temp location to the original location.
4. Run the script whenever new files are downloaded.

**Comment by Houdini111** [comment]
I took you up on suggestion 1 so I created this script to remove the artist names from their directory (so they're just ID). I decided I'd just leave the names in the files as is. 

I'll post mine here for anyone else who may want to use it. If yours doesn't follow these formats I can't guarantee that this will work fine for yours but this could be a good starting point. 

The folder format went from
`Saved/{site}/{userName}_{userId}/` to `Saved/{site}/{userId}/`
And the file format went from 
`Saved/{site}/{userName}_{userId}/{submissionId}_{title}_by_{userName}.{ext}` to `Saved/{site}/{userId}/{submissionId}_{title}_by_{userName}.{ext}`
And the album format went from 
`Saved/{site}/{userId}/{submissionId}_{title}/{submissionId}_{title}_{page}_by_{userName}.{ext}` to Saved/{site}/{userId}/{submissionId}_{title}/{submissionId}_{title}_{page}_by_{userName}.{ext}`


```py3
import os
import sys
import shutil
import pathlib


baseFolder = r"PUT THE DIRECTORY TO YOUR SITE FOLDER HERE"

artistFolders = [ f.path for f in os.scandir(baseFolder) if f.is_dir() ]



for artistFolder in artistFolders:
	artistFolderEntries = [ f.path for f in os.scandir(artistFolder) ]
	if len(artistFolderEntries) == 0:
		print(f"Artist folder empty at [{artistFolder}]. Deleting.")
		pathlib.Path.rmdir(artistFolder)
		continue
	
	artistFolderSplit = artistFolder.split('_')
	artistName = '_'.join(artistFolderSplit[:-1])
	artistId = artistFolderSplit[-1]
	newArtistDir = os.path.join(baseFolder, artistId)
	if newArtistDir == artistFolder: 
		#This is already a new format folder
		continue
		
		
	if not os.path.isdir(newArtistDir):
		#If the artist directory doesn't already exist, just rename
		print(f"To rename [{artistFolder}] to [{newArtistDir}]")
		os.rename(artistFolder, newArtistDir) 
	else:
		#If the artist directory already exists, then we have to move all the contents
		print(f"To move files from [{artistFolder}] to [{newArtistDir}]")
		file_names = os.listdir(artistFolder)
		for file_name in file_names:
			sourceLocation = os.path.join(artistFolder, file_name)
			destinationLocation = os.path.join(newArtistDir, file_name)
			if os.path.exists(destinationLocation):
				print(f"     Entry [{sourceLocation}] was supposed to be moved to [{destinationLocation}] but that already exists. Deleting instead.")
				os.remove(sourceLocation)
				continue
			print(f"     Moving entry [{sourceLocation}] to [{destinationLocation}]")
			shutil.move(os.path.join(artistFolder, file_name), newArtistDir)
		pathlib.Path.rmdir(artistFolder) #Folder should now be empty, try deleting with this safe method

print("DONE")
```
