### ISSUE TITLE
Pixiv APNG?

### ISSUE THREAD

**Issue by Heralda** [solorey/Art-Saver#48]
Would it be possible to add the ability to download animations from pixiv as APNG?

Currently all animations get downloaded as a series of individual images, and turning them into an APNG without knowing the delay between each frame is fairly work intensive. 

Ps.
Is it possible to sponsor this project?

**Comment by solorey** [comment]
Click the gear in the top right of the extension popup to go to the options page. Go the Site Options tab. In the Pixiv section there is an option for what format to save ugoira (Pixiv's name for its animations) as including ZIP, GIF, WEBM, and APNG. When using a format other than multiple files the file name will use the single file template.

I am grateful for the consideration but sponsoring this project is not available at the moment.
