### ISSUE TITLE
Hidden Deviations won't download

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#49]
There are some deviations I've just encountered where the download button doesn't work. I think it's because they were hidden in such a way that they could not be found by searching the author's gallery, but only by clicking links within other deviations in the gallery that target them.

These are the three examples I found. Most of them are NSFW:
https://www.deviantart.com/bare-faced-cheek/art/977542868
https://www.deviantart.com/bare-faced-cheek/art/962244970
https://www.deviantart.com/bare-faced-cheek/art/962391220

EDIT:
When I favorited the deviations, I could download them by clicking their download buttons from my favorites folder. But I had to click them twice, because they were marked with green check marks at first, because when I hit their download buttons on the deviations' pages and the downloads didn't go through, my Art-Saver must have mistakenly thought that they did go through. Why the button only works when the deviations are in galleries and not on their individual pages is still a mystery, though.

**Comment by solorey** [comment]
This should be fixed now in v2.0.2
