### ISSUE TITLE
Can't download from X anymore

### ISSUE THREAD

**Issue by Mirrorman95** [solorey/Art-Saver#50]
My Windows 10 computer crashed while my Art-Saver was in the middle of several X downloads. When it restarted itself, my Quick Access pins had been cleared out for the second time this month, the last six X image files Art-Saver tried to download were blank, and most importantly, the download buttons no longer appear on any X page. I can't download anything from X with Art-Saver anymore. I tried closing and reopening Firefox, I tried disabling and reenabling X support, and I tried disabling and reenabling Art-Saver, but nothing seems to fix it. The DeviantArt, InkBunny, and FurAffinity download buttons still work fine, just not X's. When I click the Art-Saver extension icon on X, I get this error:
> Unable to get site information. Error: G_state_manager is undefined

**Comment by solorey** [comment]
That error indicates that somehow the main function of the extension never runs. The site is still working on my end. Have you tried reinstalling the extension? Make sure to export your options and download data before you do.

**Comment by Mirrorman95** [comment]
I'm didn't have time to check that solution until today. When I did, the "Total users and submissions saved" table was blank, and the Export button does nothing. I know there is saved information, because there are still lots of green checkmark icons in the corners of images I've saved on various websites, except for Twitter of course. But the app doesn't seem to want to show it to me or export it. If re-installation is the only solution to my problems, you might have to talk me through extracting the saved information manually from my application data so it won't be lost.

**Comment by solorey** [comment]
Tell me if this shows anything.

- Enter `about:debugging#/runtime/this-firefox` into the URL bar
- In the ArtSaver extension click `Inspect`
- Click the `Storage` tab
- Expand and click `Extension Storage` on the left side
- Does anything show for the `twitter_saved` key?

**Comment by Mirrorman95** [comment]
> Tell me if this shows anything.
> 
>     * Enter `about:debugging#/runtime/this-firefox` into the URL bar
> 
>     * In the ArtSaver extension click `Inspect`
> 
>     * Click the `Storage` tab
> 
>     * Expand and click `Extension Storage` on the left side
> 
>     * Does anything show for the `twitter_saved` key?

I got as far as the Storage tab. It said:
No data present for selected host
Uncaught (in promise) Error: An unexpected error occurred            undefined

**Comment by solorey** [comment]
It appears the local storage has been corrupted somehow.
In the console tab of the inspector try entering each of these commands.
- `await browser.storage.local.get();`
- `await browser.storage.local.get('deviantart_saved');`
- `await browser.storage.local.get('twitter_saved'); `

Does anything return from them?

**Comment by Mirrorman95** [comment]
"await browser.storage.local.get('deviantart_saved');" returns a big list of all of the Deviants I downloaded art from. The other two just spit out more of those error messages.

**Comment by solorey** [comment]
Okay it seems like just the `twitter_saved` storage is corrupted. If you use the default file saving template it can be rebuilt.
Try `await browser.storage.local.remove('twitter_saved');` to remove the corrupted data and then see if you can export the rest of your data. If that doesn't work then let me know.

To rebuild the x (twitter) data you will need to make a JSON file.
The default save template is like this: `Saved/{site}/{userId}/{submissionId}_by_{userId}.{ext}`.
Using the `{userId}` and the `{submissionId}` create a JSON file with the following structure:
```
{
    "twitter": {
        "{userId}": ["{submissionId}", "{submissionId}", "{submissionId}", ... ],
        "{userId}": ["{submissionId}", "{submissionId}", "{submissionId}", ... ],
    }
}
```
Each key in the twitter object is a different user with it's value being an array of strings which are submission ids.
You can then import the file using the `Add saved information` in the `Saved Information` tab in the option page.

**Comment by Mirrorman95** [comment]
> Okay it seems like just the `twitter_saved` storage is corrupted. If you use the default file saving template it can be rebuilt. Try `await browser.storage.local.remove('twitter_saved');` to remove the corrupted data and then see if you can export the rest of your data. If that doesn't work then let me know.
> 
> To rebuild the x (twitter) data you will need to make a JSON file. The default save template is like this: `Saved/{site}/{userId}/{submissionId}_by_{userId}.{ext}`. Using the `{userId}` and the `{submissionId}` create a JSON file with the following structure:
> 
> ```
> {
>     "twitter": {
>         "{userId}": ["{submissionId}", "{submissionId}", "{submissionId}", ... ],
>         "{userId}": ["{submissionId}", "{submissionId}", "{submissionId}", ... ],
>     }
> }
> ```
> 
> Each key in the twitter object is a different user with it's value being an array of strings which are submission ids. You can then import the file using the `Add saved information` in the `Saved Information` tab in the option page.

Running "await browser.storage.local.remove('twitter_saved');" in the console gives me no feedback except for "1 item hidden by text filter". Am I supposed to just assume it is running properly and wait for it to finish, and if so, for how long?
(Just to be clear, the tone of my message was meant to be conveyed in a respectful way, not a sarcastic or angry way.)

**Comment by solorey** [comment]
Removing should be instant and return `undefined`. Since this also errors then copy and run this function in the console to manually get the data that is still good.
```
(async function () {
    const saved = await browser.storage.local.get([
        'deviantart_saved',
        'pixiv_saved',
        'furaffinity_saved',
        'inkbunny_saved',
    ]);
    const json_data = {};
    for ([key, value] of Object.entries(saved)) {
        json_data[key.split('_')[0]] = value;
    }
    console.log(JSON.stringify(json_data));
})();
```
Right click the output then select `Copy Object`.
Paste this data in a new file then save as `.json`.

If successful then you should be good to reinstall the extension.

**Comment by Mirrorman95** [comment]
> Removing should be instant and return `undefined`. Since this also errors then copy and run this function in the console to manually get the data that is still good.
> 
> ```
> (async function () {
>     const saved = await browser.storage.local.get([
>         'deviantart_saved',
>         'pixiv_saved',
>         'furaffinity_saved',
>         'inkbunny_saved',
>     ]);
>     const json_data = {};
>     for ([key, value] of Object.entries(saved)) {
>         json_data[key.split('_')[0]] = value;
>     }
>     console.log(JSON.stringify(json_data));
> })();
> ```
> 
> Right click the output then select `Copy Object`. Paste this data in a new file then save as `.json`.
> 
> If successful then you should be good to reinstall the extension.

Promise { <state>: "rejected", <reason>: ReferenceError }
​
<state>: "rejected"
​
<reason>: ReferenceError: browser is not defined
​​
columnNumber: 19
​​
fileName: "debugger eval code"
​​
lineNumber: 2
​​
message: "browser is not defined"
​​
stack: "@debugger eval code:2:19\n@debugger eval code:13:3\ngetEvalResult@resource://devtools/server/actors/webconsole/eval-with-debugger.js:306:26\nevalWithDebugger@resource://devtools/server/actors/webconsole/eval-with-debugger.js:218:31\nevaluateJS@resource://devtools/server/actors/webconsole.js:892:18\nevaluateJSAsync/<@resource://devtools/server/actors/webconsole.js:785:35\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22\n"

**Comment by solorey** [comment]
Glad it worked. Rebuilding the Twitter history will have to be done manually. Preferably using a scripting language that can walk through the Twitter folder and extract all the data it needs from the file names.

**Comment by solorey** [comment]
Here is an example Python script that can rebuild the Twitter data.

```py3
# A Python script that rebuild the saved twitter data
# This assumes the file name template is the same as the default
# Run the twitter folder
import os
import json

data = {}
for entry in os.scandir():
    if entry.is_dir():
        # The folder name is the user_id
        user_id = entry.name

        submissions = []
        for item in os.listdir(entry):
            # The first digits in the file or folder name are the submission id
            submission_id = item.split('_')[0]

            submissions.append(submission_id)

        data[user_id] = submissions

with open('twitter_data.json', '+w') as f:
    json.dump({'twitter': data}, f)
```
