### ISSUE TITLE
feature request: queue for download

### ISSUE THREAD

**Issue by Tinsus** [solorey/Art-Saver#7]
Hi there,

it would be very nice if every started download would be added to an internal queue, and if the download fails (for any reason), be added back to the queue (maybe optional, maybe with timeout).

reason: if you start the download on a gallery page its usually more then 10 downloads. so 10 downloads start and the rest gets cancelled. It would be very comfortable if I only need to click once and then all downloads will be completed automaticly.

**Comment by solorey** [comment]
New commit adds queue functionality. Try installing this extension temporarily and see what you think before it officially gets released.

**Comment by Tinsus** [comment]
Hi thanks for the commit - I need to tell you, that I have no idea how to build the xpi from the repository. what do I need to do, or where can I find a usable xpi for the testing?

**Comment by solorey** [comment]
No need to build anything. Just download this repository anywhere on your computer and select the `manifest.json` file when clicking `Load Temporary Addon...`.
[More information here](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)

**Comment by Tinsus** [comment]
thanks a lot, tested it: the queue works great.

**Comment by solorey** [comment]
v1.5 has been released with this functionality.
