### ISSUE TITLE
change/feature request: easy download

### ISSUE THREAD

**Issue by Tinsus** [solorey/Art-Saver#8]
Hi there,

is it possible to add a way to easy and fast (like in 1 or 2 clicks only) start the download I start by following click stream:

1) Click Icon in URL-Bar
2) Click on Stats-Icon
3) Click on the Lock to unlock the download field
4) Click on Download to start download

Ideas:
- Add new Button I can add the the urlbar, to directly start download
- add new button to start download directly on page that opens, when I clicked the URL-bar-icon
- maybe only as optional feature

**Comment by solorey** [comment]
As of v1.5 the popup will now stay in the tab you select and keep the lock unlocked. This now halves the clicks from 4 to 2. I'll keep this issue up and continue thinking about it later.
